# Generated by Django 6.0 on 2025-12-07 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre Persona')),
                ('nombre_empresa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social / Empresa')),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('direccion_principal', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(default='Lima', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(help_text='Ej: 01-443', max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('direccion_entrega', models.CharField(help_text='Dirección de envío', max_length=255)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado Completo')], default='PENDIENTE', max_length=20)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='No hay devoluciones.')),
                ('asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asesor de Venta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Guía de Entrega',
                'verbose_name_plural': 'Guías de Entrega',
            },
        ),
        migrations.CreateModel(
            name='DetalleGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.guiaentrega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
            ],
        ),
    ]
