# Generated by Django 6.0 on 2025-12-08 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_detalleguia_precio_aplicado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Empresa / Nombre')),
                ('tipo', models.CharField(choices=[('INSUMOS', 'Proveedor de Insumos/Material'), ('SERVICIOS', 'Servicios (Luz, Agua, Internet)'), ('BANCO', 'Entidad Bancaria / Prestamista'), ('OTROS', 'Otros Gastos')], default='INSUMOS', max_length=20)),
                ('ruc_dni', models.CharField(blank=True, max_length=20, verbose_name='RUC/DNI')),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Compra de 50 planchas, Recibo de Luz Agosto', max_length=200)),
                ('categoria', models.CharField(choices=[('SUMINISTRO', 'Compra de Material/Insumos'), ('OPERATIVO', 'Gasto Operativo (Luz, Local, Personal)'), ('DEUDA', 'Pago de Deuda/Préstamo')], default='SUMINISTRO', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', '⛔ Por Pagar (Deuda)'), ('PAGADO', '✅ Pagado')], default='PENDIENTE', max_length=20)),
                ('comprobante', models.CharField(blank=True, help_text='N° Factura o Boleta recibida', max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Foto o PDF de la factura', null=True, upload_to='facturas_gastos/')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.proveedor')),
            ],
        ),
    ]
