# Generated by Django 6.0 on 2026-01-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_proveedor_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaentrega',
            name='numero_guia',
            field=models.CharField(max_length=20),
        ),
    ]
