# Generated by Django 6.0 on 2026-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_perfilcolaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleguia',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
