"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nae_=9++)5)-(_!6me6c_!^5ot_aj@r^vjkmpdt1=l0ovn*wz6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',                  # <--- ESTO VA PRIMERO
    'django.contrib.admin',     # <--- El admin original va después
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- ESTA ES LA LÍNEA NUEVA
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- CONFIGURACIÓN DE JAZZMIN (INTERFAZ) ---
# --- CONFIGURACIÓN DE JAZZMIN (INTERFAZ) ---
JAZZMIN_SETTINGS = {
    "site_title": "Admin MyM",
    "site_header": "Sistema MyM",
    "site_brand": "Creaciones MyM",
    "welcome_sign": "Bienvenido al ERP",
    "search_model": ["gestion.Cliente", "gestion.GuiaEntrega"],

    "topmenu_links": [
        {"name": "🏠 Inicio (Dashboard)",  "url": "home", "permissions": ["auth.view_user"]},
        {"name": "⚙️ Configurar Tablas", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # --- HE ELIMINADO LA SECCIÓN custom_links PARA QUE NO SALGAN BOTONES REPETIDOS ---

    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "gestion.Cliente": "fas fa-user-tie",
        "gestion.Producto": "fas fa-box-open",
        "gestion.GuiaEntrega": "fas fa-file-invoice-dollar",
        "gestion.Pago": "fas fa-hand-holding-usd",
        "gestion.Proveedor": "fas fa-truck",
        "gestion.Gasto": "fas fa-money-bill-wave",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    
    # ESTO LLAMA AL SCRIPT QUE CAMBIA EL BOTÓN PRINCIPAL
    "custom_js": "gestion/js/custom_admin.js",
}

# --- REDIRECCIONES CLAVE ---
# Al iniciar sesión, te manda directo a los gráficos
LOGIN_REDIRECT_URL = 'home' 

# Al cerrar sesión, te manda al login del nuevo admin
LOGOUT_REDIRECT_URL = '/adminconfiguracion/login/'


# Colores y Tema (Estilo moderno)
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Opciones: darkly, flatly, simplex, united
    "navbar": "navbar-dark",
}
